spring:
   application:
      name: "huhu"
custom:
   property:"qnorgdemo"
   propertyslaveadded:"qnorgdemoslaveadded"
   propertyslaveaddedreally:"qnorgdemoslaveaddedmaybe really"
   propertysubtest:"qnorgdemoslaveaddedmaybe really"
   